### ISSUE TITLE
Generated string is not very random.

### ISSUE THREAD

**Issue by simstems** [simstems/Password-Generator#1]
It generates slightly different combinations of the same few characters.

From the program:

E5EEpEE5Ep
5EE555p5EE
5pEEE5p5EE
5pppp5E5EE
E5p55pEE55

This is what I got after clicking the generate button five times in a row.

**Comment by Michael-Girard** [comment]
`private static char[] charArray = {getRandomCapitalLetter(), getRandomMinusculeLetter(), getRandomNumericCharacter(), getRandomSpecialCharacter()};`

This is a compile-time initialization of this Array, meaning that when the program is compiled, it runs each one of these methods and whatever is returned is stored in the Array. So your array ended up being [E, p, 5, (whatever the special character was)] when you compiled it. Since it's never changed after that, you get similar results for each password. You could fix this by making the code similar to...

`myCharacters.append(charArray[(int)(Math.random() * 3)]);
charArray[0] = getRandomCapitalLetter();
charArray[1] = getRandomMinusculeLetter();
charArray[2] = getRandomNumericCharacter();
charArray[3] = getRandomSpecialCharacter();`

... which will randomize the contents of the array after every character. Alternatively, I made a fork in the program that features a switch and 3-4 cases that bypasses the array altogether.
